<?php

namespace GameBundle\Repository;

/**
 * DiscotechRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscotechRepository extends \Doctrine\ORM\EntityRepository
{
}
